# Generated by Django 5.0.3 on 2024-04-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_alter_contact_contact_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='user_contact',
        ),
    ]
