# Generated by Django 5.0.3 on 2024-04-11 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_rename_contact_contact_user_contact'),
        ('group', '0001_initial'),
        ('user', '0005_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='group_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacted_by_group', to='group.group'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'group_contact'), ('user', 'user_contact')},
        ),
    ]
