# Generated by Django 5.0.3 on 2024-04-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_alter_contact_unique_together_contact_group_contact_and_more'),
        ('group', '0001_initial'),
        ('user', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_group', to='group.group'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='user.user'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacted_by', to='user.user'),
        ),
    ]
