# Generated by Django 5.0.3 on 2024-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sockets',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True),
        ),
    ]
