# Generated by Django 5.0.3 on 2024-04-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_sockets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sockets',
        ),
        migrations.AddField(
            model_name='user',
            name='num_sockets',
            field=models.IntegerField(default=0),
        ),
    ]
