# Generated by Django 5.0.3 on 2024-04-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_sockets_user_num_sockets'),
        ('chat_app', '0003_alter_contact_contact_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
