# Generated by Django 5.0.3 on 2024-04-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_alter_contact_contact_alter_contact_user_and_more'),
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
